name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check clippy
      if: ${{ always() }}
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run memory tests
      run: cargo test --profile memory-test --test 'mem_test_*' --features memory_test
